# Generated by Django 6.1.1 on 2026-09-21 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Code must be 4-10 characters, uppercase letters and/or digits only.', regex='^[A-Z0-9]{4,10}$')])),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Stored as a fraction, e.g. 0.30 means 30% off.', max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('valid_til', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
