from rest_framework import serializers
from .models import Product, ProductImage


class ProductImageSerializer(serializers.ModelSerializer):
    class Meta:
        model = ProductImage
        fields = ['id', 'image', 'uploaded_at']


class ProductSerializer(serializers.ModelSerializer):
    """
    images is read_only here because ProductImage rows are created via a
    separate upload step after the product itself exists (a product needs
    an id before images can point to it via ProductImage.product FK).
    owner and serial_number are read_only — owner is set automatically
    from the logged-in user, serial_number is auto-generated by the model.
    """

    images = ProductImageSerializer(many=True, read_only=True)
    owner = serializers.ReadOnlyField(source='owner.username')

    class Meta:
        model = Product
        fields = [
            'id', 'owner', 'title', 'description', 'price',
            'stock_quantity', 'serial_number', 'images',
            'created_at', 'updated_at'
        ]
        read_only_fields = ['id', 'owner', 'serial_number', 'created_at', 'updated_at']
        
    def validate_stock_quantity(self, value):
        """
        Physical stock cannot be reduced below the amount currently
        reserved by unpaid orders.
        """
        if self.instance and value < self.instance.reserved_quantity:
            raise serializers.ValidationError(
                f'Stock quantity cannot be lower than the currently '
                f'reserved quantity ({self.instance.reserved_quantity}).'
            )

        return value