# Generated by Django 6.1.1 on 2026-09-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_payment_stripe_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='one_open_order_per_user',
        ),
    ]
