# Generated by Django 6.1.1 on 2026-10-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_product_title_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
